# Generated by Django 3.1.3 on 2020-11-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what_we_do', models.TextField(max_length=1500)),
                ('goal', models.TextField(max_length=1500)),
                ('mission', models.TextField(max_length=1500)),
                ('image', models.ImageField(upload_to='photo/')),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'Abouts',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQS',
            },
        ),
    ]
