# Generated by Django 3.1.3 on 2020-12-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='descriptin',
            field=models.TextField(default='', max_length=1500),
            preserve_default=False,
        ),
    ]
