# Generated by Django 3.1.3 on 2020-12-11 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_faq_descriptin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='descriptin',
            new_name='description',
        ),
    ]
