# Generated by Django 3.1.3 on 2020-11-27 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20201127_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='location',
            field=models.CharField(max_length=200),
        ),
    ]
