# Generated by Django 3.1.3 on 2020-12-16 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_auto_20201216_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roombook',
            name='email',
        ),
    ]
