# Generated by Django 3.1.3 on 2020-12-16 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_remove_roombook_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roombook',
            old_name='name',
            new_name='user',
        ),
    ]
