# Generated by Django 3.1.3 on 2020-12-16 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20201216_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roombook',
            old_name='user',
            new_name='name',
        ),
    ]
