# Generated by Django 3.1.3 on 2020-12-24 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20201216_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roombook',
            old_name='from_data',
            new_name='from_date',
        ),
        migrations.RenameField(
            model_name='roombook',
            old_name='to_data',
            new_name='to_date',
        ),
    ]
