# Generated by Django 3.1.3 on 2021-01-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_roomreview_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
