# Generated by Django 3.1.3 on 2021-01-03 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='room_place', to='property.place'),
            preserve_default=False,
        ),
    ]
