# Generated by Django 3.1.3 on 2021-01-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_auto_20210103_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
